name: 'Setup Config Files'
description: 'Setup local.properties and keystore files for Android build'

inputs:
    # local.properties
    server-base-url:
        required: false
        default: 'https://dummy.com'
    amplitude-api-key:
        required: false
        default: ''
    piece-dev-base-url:
        required: false
        default: ''
    piece-prod-base-url:
        required: false
        default: ''
    piece-notice-url:
        required: false
        default: ''
    piece-privacy-and-policy-url:
        required: false
        default: ''
    piece-terms-of-use-url:
        required: false
        default: ''
    piece-channel-talk-url:
        required: false
        default: ''
    piece-market-url:
        required: false
        default: ''
    google-web-client-id:
        required: false
        default: ''

    # keystore
    keystore-base64:
        required: false
        default: ''
    store-password:
        required: false
        default: 'dummy-store-password'
    key-alias-release:
        required: false
        default: 'dummy-release-alias'
    key-password-release:
        required: false
        default: 'dummy-release-password'
    key-alias-debug:
        required: false
        default: 'dummy-debug-alias'
    key-password-debug:
        required: false
        default: 'dummy-debug-password'

runs:
    using: 'composite'
    steps:
        -   name: Set up local.properties
            shell: bash
            run: |
                if [ -n "${{ inputs.server-base-url }}" ]; then
                  echo "KKH_SERVER_BASE_URL=${{ inputs.server-base-url }}" >> local.properties
                else
                  touch local.properties
                fi

        -   name: Set up keystore
            shell: bash
            run: |
                if [ -n "${{ inputs.keystore-base64 }}" ]; then
                  echo "${{ inputs.keystore-base64 }}" | base64 --decode > ./app/upload-keystore.jks
                  echo "STORE_FILE_PATH=./upload-keystore.jks" >> keystore.properties
                else
                  echo "STORE_FILE_PATH=dummy.jks" >> keystore.properties
                fi
                echo "STORE_PASSWORD=${{ inputs.store-password }}" >> keystore.properties
                echo "KEY_ALIAS_RELEASE=${{ inputs.key-alias-release }}" >> keystore.properties
                echo "KEY_PASSWORD_RELEASE=${{ inputs.key-password-release }}" >> keystore.properties
                echo "KEY_ALIAS_DEBUG=${{ inputs.key-alias-debug }}" >> keystore.properties
                echo "KEY_PASSWORD_DEBUG=${{ inputs.key-password-debug }}" >> keystore.properties
